name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-docker:latest
    - name: Docker Pull & Run From Hub
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker login
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/react-docker:latest
          docker stop react-docker-container 
          docker container rm react-docker-container 
          docker image rm claudiateng/react-docker
          docker run -d -p 80:80 --name react-docker-container ${{ secrets.DOCKER_HUB_USERNAME }}/react-docker:latest
